@startuml Domæne-model til Budweg
Class Station {
    stationsType
    stationsNavn
}

Class Bremsekaliber {
    bremsekaliberType
    bremsekaliberStatus
    stregkode
    kaliberNummer
    ordreNummer
    note
}

note right of Bremsekaliber
    Forretningsregler (UC1)
    - Kaliber skal have stregkode før scanning
    - Hvis scanning fejler, kan stregkode indtastes manuelt
    - Ved "send til næste station" opdateres status
    - Kaliber skal være registreret i systemet
end note

Class Renoveringstatus <<enumeration>> {
    modtaget
    adskilt
    kasseret
    afsendt
}

Class  Reservedel{
   reservedelsType
   reservedelsMængde
}

Reservedel "0..*" -- "1..*" Station
Renoveringstatus .. Bremsekaliber
Bremsekaliber "0..*" -- "1..*" Station

hide circle
hide methods
@enduml