@startsalt Wireframe
{+
  {
    <b>mainwindow
    --
    {
      "  = Budweg  "
    }
  }
  {+
    .
    [      ModtagBremsekaliber      ]
    [      AfsendBremsekaliber      ]
    [      Kassér      ]
    [       Note       ]
    [   Kaliberinfo    ]
    .
    --
    {
      .
      "Indhold indlæses her..."
      .
      .
      .
      .
    }
  }
  
}
@endsalt