@startuml Domæne-model til Budweg
Class Station {
    stationsType
    stationsNavn
}

Class Bremsekaliber {
    bremsekaliberType
    bremsekaliberStatus
    stregkode
    kaliberNummer
    ordreNummer
    note
}

note right of Bremsekaliber
    Forretningsregler (UC1):
    - Budweg modtager partier af brugte bremsekalibre

    - Disse kalibre er pakket i emballage med 
      stregkode som indeholder varenummer.

    - De bliver sorteret efter bremsekalibermodel 
      (vha. stregkode fra emballage), og lagt på lager.
      
    - Når et parti af bremsekalibre skal renoveres, får hver kaliber
      af samme type et klistermærke med en stregkode, 
      der er unik for den enkelte kaliber.

end note

Class Renoveringstatus <<enumeration>> {
    modtaget
    adskilt
    kasseret
    afsendt
}

Class  Reservedel{
   reservedelsType
   reservedelsMængde
}

Reservedel "0..*" -- "1..*" Station
Renoveringstatus .. Bremsekaliber
Bremsekaliber "0..*" -- "1..*" Station

hide circle
hide methods
@enduml