@startuml - Designklassediagram (DCD) Budweg
left to right direction 

package "ViewModel (Application)"{
    class BremsekaliberRepository {
        - bremsekaliber : Bremsekaliber[0..*] 
        + CreateBremsekaliber()
        + FindByStregkode(stregkode: String): Bremsekaliber
        + MoveToNextStation(kaliberNummer: String)
        + UpdateStatus(kaliberNummer: String, status: Renoveringstatus)
        + ListByStation(stationsNavn: String): Bremsekaliber[0..*]
        
    }
    class StationRepository {
            - station : Station[0..*] 
            + CreateStation()
        + FindByName(stationsNavn: String): Station
        + ListAllStations(): Station[0..*]
        + GetNextStation(stationsNavn: String): Station
    }
    class ReservedelRepository {
        - reservedel : Reservedel[0..*]
        + CreateReservedel()
        + FindByStation(stationsNavn: String): Reservedel[0..*]
        + AddReservedel(reservedelsType: String, reservedelsMængde: int, stationsNavn: String)
        + UpdateQuantity(reservedelsType: String, reservedelsMængde: int)
    }
    class Controller {
        + RegisterBremsekaliber(stregkode: String, kaliberNummer: String, ordreNummer: String)
        + ReceiveBremsekaliber(stregkode: String)
        + SendBremsekaliber(stregkode: String)
    }
}

package "Model (Domain)" {
    class Station {
        - stationsType: String
        - stationsNavn: String
        + Station()
    }

    class Bremsekaliber {
        - bremsekaliberType: String
        - bremsekaliberStatus: String
        - stregkode: String
        - kaliberNummer: String
        - ordreNummer: String 
        - note: String
        + Bremsekaliber() 
    }

    class Renoveringstatus <<enumeration>> {
        modtaget
        adskilt
        kasseret
        afsendt
    }

    class Reservedel{
       - reservedelsType: String
       - reservedelsMængde: int
       + Reservedel()
    }
}



Controller .. StationRepository
Controller .. BremsekaliberRepository
Controller .. ReservedelRepository

StationRepository .. Station
BremsekaliberRepository .. Bremsekaliber
ReservedelRepository .. Reservedel

Bremsekaliber "0..*" -- "1..*" Station
Renoveringstatus .. Bremsekaliber
Reservedel "0..*" -- "1..*" Station


hide circle

@enduml