@startuml - Design Class Diagram (DCD) Budweg
left to right direction 

package "ViewModel (Application)"{
    class MainViewModel {
        - brakeCaliperRepository: BrakeCaliperRepository
        - stationRepository: StationRepository
        - sparePartRepository: SparePartRepository
        + MainViewModel(brakeCaliperRepository: BrakeCaliperRepository,
        stationRepository: StationRepository, sparePartRepository: SparePartRepository)
    }
}

package "Infrastructure (Repositories)" {
    class BrakeCaliperRepository {
        - brakeCaliper : BrakeCaliper[0..*]
        + CreateBrakeCaliper()
        + FindByBarcode(barcode: String): BrakeCaliper
        + MoveToNextStation(caliperNumber: String)
        + UpdateStatus(caliperNumber: String, status: ProcessingStatus)
        + ListByStation(stationName: String): BrakeCaliper[0..*]

    }
    class StationRepository {
            - station : Station[0..*] 
            + CreateStation()
        + FindByName(stationName: String): Station
        + ListAllStations(): Station[0..*]
        + GetNextStation(stationName: String): Station
    }
    class SparePartRepository {
        - sparePart : SparePart[0..*]
        + CreateSparePart()
        + FindByStation(stationName: String): SparePart[0..*]
        + AddSparePart(sparePartType: String, sparePartQuantity: int, stationName: String)
        + UpdateQuantity(sparePartType: String, sparePartQuantity: int)
    }
}

package "Model (Domain)" {
    class Station {
        - stationType: String
        - stationName: String
        + Station()
    }

    class BrakeCaliper {
        - caliperType: String
        - caliperStatus: ProcessingStatus
        - barcode: String
        - caliperNumber: String
        - orderNumber: String 
        - note: String
        + BrakeCaliper() 
    }

    class ProcessingStatus <<enumeration>> {
        received
        disassembled
        scrapped
        dispatched
    }

    class SparePart{
       - sparePartType: String
       - sparePartQuantity: int
       + SparePart()
    }
}



MainViewModel .. StationRepository
MainViewModel .. BrakeCaliperRepository
MainViewModel .. SparePartRepository

StationRepository .. Station
BrakeCaliperRepository .. BrakeCaliper
SparePartRepository .. SparePart

BrakeCaliper "0..*" -- "1..*" Station
ProcessingStatus .. BrakeCaliper
SparePart "0..*" -- "1..*" Station


hide circle

@enduml