@startuml SSD
title <u>Scan og flyt kaliber til næste station </u>

Actor ": Medarbejder" as Medarbejder
participant ": System" as System

Medarbejder -> System: ModtagBremseKaliber(Status)
System --> Medarbejder: Systemet har registreret id'et
System --> Medarbejder: Systemet har registreret status og station

Medarbejder -> System: AfsendBremseKaliber(Status)
System --> Medarbejder: Registreret som afsendt
System --> Medarbejder: Systemet bekræfter og gemmer


hide footbox

@enduml
